apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-world-pipeline-run-
spec:
  pipelineSpec:
    tasks:
      - name: hello-task
        taskSpec:
          steps:
            - name: print-hello
              image: ubuntu
              script: |
                #!/bin/sh
                echo "Hello, World from Tekton!"
