# apiVersion: tekton.dev/v1beta1
# kind: Pipeline
# metadata:
#   name: hello-world-pipeline
# spec:
#   tasks:
#     - name: hello-task
#       taskSpec:
#         steps:
#           - name: print-hello
#             image: ubuntu
#             script: |
#               #!/bin/sh
#               echo "Hello, World from Tekton......!"
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch-name
      type: string
    - name: api-key
      type: string
    - name: access-token
      type: string
  tasks:
    - name: hello-task
      taskSpec:
        steps:
          - name: print-hello
            image: ubuntu
            script: |
              #!/bin/sh
              echo "Hello, World from Tekton......!"
              echo "Repository URL: $(params.repo-url)"
              echo "Branch Name: $(params.branch-name)"
              echo "API Key: $(params.api-key)"
              echo "Access Token: $(params.access-token)"
