# # apiVersion: triggers.tekton.dev/v1beta1
# # kind: EventListener
# # metadata:
# #   name: hello-world-listener
# # spec:
# #   triggers:
# #     - name: git-push-trigger
# #       bindings:
# #         - ref: git-binding
# #       template:
# #         ref: pipeline-template

# # ---
# # apiVersion: triggers.tekton.dev/v1beta1
# # kind: TriggerBinding
# # metadata:
# #   name: git-binding
# # spec:
# #   params:
# #     - name: git-repo-url
# #       value: "$(body.repository.clone_url)"
# #     - name: git-revision
# #       value: "$(body.ref)"

# # ---
# # apiVersion: triggers.tekton.dev/v1beta1
# # kind: TriggerTemplate
# # metadata:
# #   name: pipeline-template
# # spec:
# #   params:
# #     - name: git-repo-url
# #     - name: git-revision
# #   resourcetemplates:
# #     - apiVersion: tekton.dev/v1beta1
# #       kind: PipelineRun
# #       metadata:
# #         generateName: hello-world-pipeline-run-
# #       spec:
# #         pipelineRef:
# #           name: hello-world-pipeline
# #         workspaces:
# #           - name: shared-data
# #             emptyDir: {}
# #         params:
# #           - name: git-url
# #             value: "$(params.git-repo-url)"
# #           - name: git-revision
# #             value: "$(params.git-revision)"
# apiVersion: triggers.tekton.dev/v1beta1
# kind: EventListener
# metadata:
#   name: hello-world-listener
# spec:
#   triggers:
#     - name: git-push-trigger
#       bindings:
#         - ref: git-binding
#       template:
#         ref: pipeline-template
#     - name: generic-trigger
#       bindings:
#         - ref: generic-binding
#       template:
#         ref: pipeline-template

# ---
# apiVersion: triggers.tekton.dev/v1beta1
# kind: TriggerBinding
# metadata:
#   name: git-binding
# spec:
#   params:
#     - name: git-repo-url
#       value: "$(body.repository.clone_url)"
#     - name: git-revision
#       value: "$(body.ref)"

# ---
# apiVersion: triggers.tekton.dev/v1beta1
# kind: TriggerBinding
# metadata:
#   name: generic-binding
# spec:
#   params:
#     - name: event-payload
#       value: "$(body)"  # Captures the entire webhook payload
#     - name: custom-param
#       value: "$(body.custom_field)"  # Extract a specific field from webhook payload

# ---
# apiVersion: triggers.tekton.dev/v1beta1
# kind: TriggerTemplate
# metadata:
#   name: pipeline-template
# spec:
#   params:
#     - name: git-repo-url
#     - name: git-revision
#     - name: event-payload
#     - name: custom-param
#   resourcetemplates:
#     - apiVersion: tekton.dev/v1beta1
#       kind: PipelineRun
#       metadata:
#         generateName: hello-world-pipeline-run-
#       spec:
#         pipelineRef:
#           name: hello-world-pipeline
#         workspaces:
#           - name: shared-data
#             emptyDir: {}
#         params:
#           - name: git-url
#             value: "$(params.git-repo-url)"
#           - name: git-revision
#             value: "$(params.git-revision)"
#           - name: event-payload
#             value: "$(params.event-payload)"
#           - name: custom-param
#             value: "$(params.custom-param)"
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-world-listener
spec:
  triggers:
    - name: git-push-trigger
      bindings:
        - ref: git-binding
      template:
        ref: pipeline-template
    - name: generic-trigger
      bindings:
        - ref: generic-binding
      template:
        ref: pipeline-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: git-binding
spec:
  params:
    - name: git-repo-url
      value: "$(body.repository.clone_url)"
    - name: git-revision
      value: "$(body.ref)"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: generic-binding
spec:
  params:
    - name: event-payload
      value: "$(body)"  # Captures the entire webhook payload
    - name: custom-param
      value: "$(body.custom_field)"  # Extract a specific field from webhook payload
    - name: secret-1
      value: "$(body.secret_1)"   # Example: Fetch from webhook payload
    - name: secret-2
      value: "$(body.secret_2)"
    - name: text-1
      value: "$(body.text_1)"
    - name: text-2
      value: "$(body.text_2)"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - name: git-repo-url
    - name: git-revision
    - name: event-payload
    - name: custom-param
    - name: secret-1
    - name: secret-2
    - name: text-1
    - name: text-2
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: hello-world-pipeline-run-
      spec:
        pipelineRef:
          name: hello-world-pipeline
        workspaces:
          - name: shared-data
            emptyDir: {}
        params:
          - name: git-url
            value: "$(params.git-repo-url)"
          - name: git-revision
            value: "$(params.git-revision)"
          - name: event-payload
            value: "$(params.event-payload)"
          - name: custom-param
            value: "$(params.custom-param)"
          - name: secret-1
            value: "$(params.secret-1)"
          - name: secret-2
            value: "$(params.secret-2)"
          - name: text-1
            value: "$(params.text-1)"
          - name: text-2
            value: "$(params.text-2)"
